name = "CapacitatedAssignmentProblem"
defaultTargets = ["CapacitatedAssignmentProblem"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "f34e762642b3470574f0117a100a8fc4eaeae651"

[[lean_lib]]
name = "CapacitatedAssignmentProblem"
